In [6]:
from PIL import Image
from transformers import Qwen2VLForConditionalGeneration, Qwen2VLImageProcessor, AutoProcessor
from qwen_vl_utils import process_vision_info
import gradio as gr
import zipfile
import os
import numpy as np
import random
import shutil
import pandas as pd
import cv2
from qwen import read_blue_channel
import yaml
from qwen import read_red_channel, read_green_channel, read_blue_channel, extract_zip_path, generate_random_sample, red_green_channel
from langchain.prompts import PromptTemplate
from langchain.chat_models import ChatOpenAI
from langchain.chains import LLMChain
import json
import torch

c:\Users\archi\anaconda3\envs\asid\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
c:\Users\archi\anaconda3\envs\asid\lib\site-packages\torchvision\datapoints\__init__.py:12: UserWarning: The torchvision.datapoints and torchvision.transforms.v2 namespaces are still Beta. While we do not expect major breaking changes, some APIs may still change according to user feedback. Please submit any feedback you may have in this issue: https://github.com/pytorch/vision/issues/6753, and you can also check out https://github.com/pytorch/vision/issues/7319 to learn more about the APIs that we suspect might involve future changes. You can silence this warning by calling torchvision.disable_beta_transforms_warning().
  warnings.warn(_BETA_TRANSFORMS_WARNING)
c:\Users\archi\anaconda3\envs\asid\lib\site-packages\torchvision\transforms\v2\__init__.py:54: UserWarning: The torchvision.datapoints and torchvision.transforms.v2 namespaces are still Beta. While we do not expect major breaking changes, some APIs may still change according to user feedback. Please submit any feedback you may have in this issue: https://github.com/pytorch/vision/issues/6753, and you can also check out https://github.com/pytorch/vision/issues/7319 to learn more about the APIs that we suspect might involve future changes. You can silence this warning by calling torchvision.disable_beta_transforms_warning().
  warnings.warn(_BETA_TRANSFORMS_WARNING)

## Load Data

In [7]:
HOME = os.path.expanduser('~') + "\\ecdna-analysis"
config_path = os.path.join(HOME, "config.yaml")

config = open(config_path)
var = yaml.load(config, Loader=yaml.FullLoader)['qwen']

zip_file_path = os.path.join(HOME, var['zipfile_path'])
test_folder_name = var['test_folder_name']
test_extract_folder = os.path.join(HOME, var['test_extract_folder'])
train_folder_name = var['train_folder_name']
train_extract_folder = os.path.join(HOME, var['train_extract_folder'])

extract_zip_path(zip_file_path, train_folder_name, train_extract_folder)
extract_zip_path(zip_file_path, test_folder_name, test_extract_folder)

sample_size = var['sample_size']
input_folder = os.path.join(test_extract_folder , f'ecSeg_dataset\\{test_folder_name}')
output_folder = os.path.join(HOME, var['sampled'] )

test_images = os.path.join(test_extract_folder , f'ecSeg_dataset\\{test_folder_name}')
train_images = os.path.join(train_extract_folder , f'ecSeg_dataset\\{train_folder_name}')

## Model Initialization

In [8]:
# Initialize the tokenizer and the model name (using the Qwen2-VL 2B-Instruct model)
model_name = "Qwen/Qwen2-VL-2B-Instruct"
model = Qwen2VLForConditionalGeneration.from_pretrained(
    model_name, torch_dtype="auto", device_map="auto"
)
processor = AutoProcessor.from_pretrained(model_name)
image_processor = Qwen2VLImageProcessor.from_pretrained(model_name)

`Qwen2VLRotaryEmbedding` can now be fully parameterized by passing the model config through the `config` argument. All other arguments will be removed in v4.46
Loading checkpoint shards: 100%|██████████| 2/2 [00:06<00:00,  3.43s/it]

In [9]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(device)
model = model.to(device)
model.get_parameter

cuda

<bound method Module.get_parameter of Qwen2VLForConditionalGeneration(
  (visual): Qwen2VisionTransformerPretrainedModel(
    (patch_embed): PatchEmbed(
      (proj): Conv3d(3, 1280, kernel_size=(2, 14, 14), stride=(2, 14, 14), bias=False)
    )
    (rotary_pos_emb): VisionRotaryEmbedding()
    (blocks): ModuleList(
      (0-31): 32 x Qwen2VLVisionBlock(
        (norm1): LayerNorm((1280,), eps=1e-06, elementwise_affine=True)
        (norm2): LayerNorm((1280,), eps=1e-06, elementwise_affine=True)
        (attn): VisionAttention(
          (qkv): Linear(in_features=1280, out_features=3840, bias=True)
          (proj): Linear(in_features=1280, out_features=1280, bias=True)
        )
        (mlp): VisionMlp(
          (fc1): Linear(in_features=1280, out_features=5120, bias=True)
          (act): QuickGELUActivation()
          (fc2): Linear(in_features=5120, out_features=1280, bias=True)
        )
      )
    )
    (merger): PatchMerger(
      (ln_q): LayerNorm((1280,), eps=1e-06, elementwise_affine=True)
      (mlp): Sequential(
        (0): Linear(in_features=5120, out_features=5120, bias=True)
        (1): GELU(approximate='none')
        (2): Linear(in_features=5120, out_features=1536, bias=True)
      )
    )
  )
  (model): Qwen2VLModel(
    (embed_tokens): Embedding(151936, 1536)
    (layers): ModuleList(
      (0-27): 28 x Qwen2VLDecoderLayer(
        (self_attn): Qwen2VLAttention(
          (q_proj): Linear(in_features=1536, out_features=1536, bias=True)
          (k_proj): Linear(in_features=1536, out_features=256, bias=True)
          (v_proj): Linear(in_features=1536, out_features=256, bias=True)
          (o_proj): Linear(in_features=1536, out_features=1536, bias=False)
          (rotary_emb): Qwen2VLRotaryEmbedding()
        )
        (mlp): Qwen2MLP(
          (gate_proj): Linear(in_features=1536, out_features=8960, bias=False)
          (up_proj): Linear(in_features=1536, out_features=8960, bias=False)
          (down_proj): Linear(in_features=8960, out_features=1536, bias=False)
          (act_fn): SiLU()
        )
        (input_layernorm): Qwen2RMSNorm((1536,), eps=1e-06)
        (post_attention_layernorm): Qwen2RMSNorm((1536,), eps=1e-06)
      )
    )
    (norm): Qwen2RMSNorm((1536,), eps=1e-06)
    (rotary_emb): Qwen2VLRotaryEmbedding()
  )
  (lm_head): Linear(in_features=1536, out_features=151936, bias=False)
)>

# Generating Results

In [10]:
# Load train data into a df
train_df = pd.read_csv(HOME + '\\train_images_counts.csv')
train_df

         image  num_nuclei  num_chromosomes  num_ecDNA
0     2343.tif           1                0          0
1     2344.tif           2                0          0
2     2345.tif           0                5          0
3     2346.tif           0               18          0
4     2347.tif           1                6          1
...        ...         ...              ...        ...
4755  9653.tif           0                2          2
4756  9655.tif           2                0          0
4757  9657.tif           1                0          0
4758  9658.tif           2                0          0
4759  9659.tif           2                7          3

[4760 rows x 4 columns]

In [11]:
# Load test data into a df
test_df = pd.read_csv(HOME + '\\test_images_counts.csv')
test_df

         image  num_nuclei  num_chromosomes  num_ecDNA
0        0.tif           2                1          1
1        1.tif           4                1          3
2       10.tif           1                6          2
3     1000.tif           3                4          2
4     1001.tif           1                0          0
...        ...         ...              ...        ...
1184   992.tif           0                6          0
1185   993.tif           0               18          3
1186   994.tif           0               26          0
1187   995.tif           0               17          5
1188   998.tif           0                3          0

[1189 rows x 4 columns]

# Experiments

In [103]:
# Define system message
system_message = '''
    You are a pathologist analyzing metaphase cell images. These images contain three main structures: ecDNA, nuclei, and chromosomes. Your goal is to focus on connected component analysis in the image.
'''
n_shots = [0, 1, 2, 3]
temperatures = [0.3, 0.5, 0.7, 0.9]
num_trials = 5
questions_list = [
    'Describe this image.',
    'How many connected components do you see?',
    'describe the ecDNA patterns in this image.'
]

In [64]:
train_df.sample(3)

         image  num_nuclei  num_chromosomes  num_ecDNA
3571  7808.tif           0                7          0
851   3556.tif           2                0          0
1457  4374.tif           2               28          6

### N-Shot Learning

In [76]:
def qwen2_n_shot(
    image,
    n_shots,
    system_message = '',
    root_folder = test_images,
    top_k = 10,
    top_p = 0.8,
    do_sample = True,
    repetition_penalty = 1.05,
    train_df = train_df,
    train_folder = train_images
):
    '''
        Run an N-shot experiment.
        Input:
            image: test image
            n_shots: number of N-shot learning experiments (must be a list)
        Output:
        list of responses for each experiment
    '''
    img_path = os.path.join(root_folder, image)
    test_image = Image.open(img_path)

    # Sample images from train dataframe
    images = []
    result = []
    for n in n_shots:
        if n != 0:
            # Sample images from train to provide as context
            sampled_train = train_df.sample(n, replace=False)
            counts = [sampled_train['num_ecDNA'].iloc[i] for i in range(n)]
            images = [Image.open(os.path.join(train_folder, sampled_train['image'].iloc[i])) for i in range(n)]

        conversation = [
            {
                'role': 'user',
                'content': f'{system_message} ecDNA are circular structures in cell images.'
            }
        ]

        for i in range(n):
            conversation.append({
                'role': 'user',
                'content': [
                    {'type': 'image', 'image': images[i]},
                    {'type': 'text', 'text': f"This is a cell image containing {counts[i]} ecDNA"}
                ]
            })

            conversation.append({
                'role': 'assistant',
                'content': 'Thank you for the information. I see that the image has {counts[i]} ecDNA.'
            })
        
        prompt = PromptTemplate(
            template = 
            '''
                How many ecDNA are in the image? Return an integer number in JSON format.
            '''
        )
        formatted_prompt = prompt.format()

        conversation.append({
            'role': 'user',
            'content': [
                {'type': 'image', 'image': test_image},
                {'type': 'text', 'text': formatted_prompt}
            ]
        })

        text = processor.apply_chat_template(
            conversation, tokenize=False, add_generation_prompt=True, add_vision_id=True
        )

        inputs = processor(
                text=[text],
                padding=True,
                return_tensors="pt",
        )

        inputs = inputs.to(device)

        generated_ids = model.generate(
            **inputs,
            max_new_tokens=128,
            top_k=top_k,
            top_p=top_p,
            repetition_penalty=repetition_penalty,
            do_sample=do_sample
        )

        generated_ids_trimmed = [
            out_ids[len(in_ids):] for in_ids, out_ids in zip(inputs.input_ids, generated_ids)
        ]

        output_text = processor.batch_decode(generated_ids_trimmed, skip_special_tokens=True, clean_up_tokenization_spaces=False
        )[0]

        result.append(output_text)
    
    return result

In [100]:
# Test the function
qwen2_n_shot(test_df['image'].iloc[510], n_shots, system_message=system_message)

['{\n  "ecDNA": 0\n}',
 '```json\n[8]\n```',
 '{\n  "ecDNA": 4\n}',
 '```json\n[3]\n```']

In [80]:
test_df['n_shot'] = test_df['image'].apply(lambda x: qwen2_n_shot(x, n_shots, system_message=system_message))

### Multi-Layered Prompts

In [114]:
def qwen2_multi_layer(
        image,
        questions_list,
        root_folder = test_images,
        top_k = 10,
        top_p = 0.95,
        do_sample = True,
        repetition_penalty = 1.05
):
    '''
        This function runs a multi-layered prompt experiment.
        Inputs:
        
        Returns:

    '''
    img_path = os.path.join(root_folder, image)
    test_image = Image.open(img_path)

    prompt = PromptTemplate(
            template = 
            '''
                How many ecDNA are in the image? Return an integer number in JSON format.
            '''
        )
    
    formatted_prompt = prompt.format()
    # Sample images from train dataframe

    conversation = [
        {
            'role': 'user',
            'content': f'{system_message} ecDNA are circular structures in cell images.'
        },
    ]

    for question in questions_list:
        conversation.append({
            'role': 'user',
            'content': [
                {'type': 'image', 'image': test_image},
                {'type': 'text', 'text': question}
            ]
        })

        text = processor.apply_chat_template(
                conversation, tokenize=False, add_generation_prompt=True, add_vision_id=True
            )

        inputs = processor(
                text=[text],
                padding=True,
                return_tensors="pt",
        )

        inputs = inputs.to(device)

        generated_ids = model.generate(
            **inputs,
            max_new_tokens=128,
            top_k=top_k,
            top_p=top_p,
            repetition_penalty=repetition_penalty,
            do_sample=do_sample
        )

        generated_ids_trimmed = [
            out_ids[len(in_ids):] for in_ids, out_ids in zip(inputs.input_ids, generated_ids)
        ]

        output_text = processor.batch_decode(generated_ids_trimmed, skip_special_tokens=True, clean_up_tokenization_spaces=False
        )[0]

        conversation.append({
            'role': 'assistant',
            'content': output_text
        })

    # Generate final output result
    conversation.append({
            'role': 'user',
            'content': [
                {'type': 'image', 'image': test_image},
                {'type': 'text', 'text': formatted_prompt}
            ]
    })

    text = processor.apply_chat_template(
                conversation, tokenize=False, add_generation_prompt=True, add_vision_id=True
            )

    inputs = processor(
            text=[text],
            padding=True,
            return_tensors="pt",
    )

    inputs = inputs.to(device)

    generated_ids = model.generate(
        **inputs,
        max_new_tokens=128,
        top_k=top_k,
        top_p=top_p,
        temperature=0.6,
        repetition_penalty=repetition_penalty,
        do_sample=do_sample
    )

    generated_ids_trimmed = [
        out_ids[len(in_ids):] for in_ids, out_ids in zip(inputs.input_ids, generated_ids)
    ]

    output_text = processor.batch_decode(generated_ids_trimmed, skip_special_tokens=True, clean_up_tokenization_spaces=False
    )[0]

    return output_text

In [ ]:
test_df['multi_layer'] = test_df['image'].apply(lambda x: qwen2_multi_layer(x, questions_list))
test_df.to_csv(HOME + '\\qwen\\experiment_final_results.csv')

'```json\n{\n  "ecDNA": 2\n}\n```'

### Aggregating Over Multiple Trials

In [96]:
def qwen2_agg_results(
        image,
        num_trials,
        system_message = '',
        root_folder = test_images,
        top_k = 10,
        top_p = 0.95,
        do_sample = True,
        repetition_penalty = 1.05
):
    img_path = os.path.join(root_folder, image)
    test_image = Image.open(img_path)

    prompt = PromptTemplate(
            template = 
            '''
                How many ecDNA are in the image? Return an integer number in JSON format.
            '''
        )
    formatted_prompt = prompt.format()
    # Sample images from train dataframe
    result = []

    conversation = [
        {
            'role': 'user',
            'content': f'{system_message} ecDNA are circular structures in cell images.'
        },
        {
            'role': 'user',
            'content': [
                {'type': 'image', 'image': test_image},
                {'type': 'text', 'text': formatted_prompt}
            ]
        }
    ]

    for i in range(num_trials):

        text = processor.apply_chat_template(
                conversation, tokenize=False, add_generation_prompt=True, add_vision_id=True
            )

        inputs = processor(
                text=[text],
                padding=True,
                return_tensors="pt",
        )

        inputs = inputs.to(device)

        generated_ids = model.generate(
            **inputs,
            max_new_tokens=128,
            top_k=top_k,
            top_p=top_p,
            repetition_penalty=repetition_penalty,
            do_sample=do_sample
        )

        generated_ids_trimmed = [
            out_ids[len(in_ids):] for in_ids, out_ids in zip(inputs.input_ids, generated_ids)
        ]

        output_text = processor.batch_decode(generated_ids_trimmed, skip_special_tokens=True, clean_up_tokenization_spaces=False
        )[0]

        result.append(output_text)

    return result

In [102]:

test_df['agg_results'] = test_df['image'].apply(lambda x: qwen2_agg_results(x, num_trials, system_message=system_message))
test_df.to_csv(HOME + '\\qwen\\experiment_results.csv')

### Temperature Adjustment

In [83]:
def qwen2_temp_adj(
    image,
    temperatures,
    system_message = '',
    root_folder = test_images,
    top_k = 10,
    top_p = 0.8,
    do_sample = True,
    repetition_penalty = 1.05,
    train_df = train_df,
    train_folder = train_images
):
    '''
        Run an N-shot experiment.
        Input:
            image: test image
            n_shots: number of N-shot learning experiments (must be a list)
        Output:
        list of responses for each experiment
    '''
    img_path = os.path.join(root_folder, image)
    test_image = Image.open(img_path)

    # Sample images from train dataframe
    images = []
    result = []
    for temp in temperatures:

        conversation = [
            {
                'role': 'user',
                'content': f'{system_message} ecDNA are circular structures in cell images.'
            }
        ]

        prompt = PromptTemplate(
            template = 
            '''
                How many ecDNA are in the image? Return an integer number in JSON format.
            '''
        )
        formatted_prompt = prompt.format()

        conversation.append({
            'role': 'user',
            'content': [
                {'type': 'image', 'image': test_image},
                {'type': 'text', 'text': formatted_prompt}
            ]
        })

        text = processor.apply_chat_template(
            conversation, tokenize=False, add_generation_prompt=True, add_vision_id=True
        )

        inputs = processor(
            text=[text],
            padding=True,
            return_tensors="pt",
        )

        inputs = inputs.to(device)

        generated_ids = model.generate(
            **inputs,
            max_new_tokens=128,
            temperature = temp,
            top_k=top_k,
            top_p=top_p,
            repetition_penalty=repetition_penalty,
            do_sample=do_sample
        )

        generated_ids_trimmed = [
            out_ids[len(in_ids):] for in_ids, out_ids in zip(inputs.input_ids, generated_ids)
        ]

        output_text = processor.batch_decode(generated_ids_trimmed, skip_special_tokens=True, clean_up_tokenization_spaces=False
        )[0]

        result.append(output_text)
    
    return result

In [ ]:
# test_df.to_csv(HOME + '\\qwen\\experiment_results.csv')

In [ ]:
# test_df['temp_adj'] = test_df['image'].apply(lambda x: qwen2_temp_adj(x, temperatures, system_message=system_message))

In [ ]:
# Load data into a CSV
test_df.to_csv(HOME + '\\qwen\\experiment_3_results.csv')

In [ ]:
def generate_results(messages, images, temperature, top_k, top_p, do_sample, ):
     # Generate results
    text = processor.apply_chat_template(
            messages, tokenize=False, add_generation_prompt=True, add_vision_id=True
        )

    # Create inputs to be passed into the model
    inputs = processor(
        text=[text],
        images=images,
        padding=True,
        return_tensors="pt",
    )

    inputs = inputs.to(device)

    generated_ids = model.generate(
            **inputs, max_new_tokens=128,
            temperature=0.7,  
            top_k=10,         
            top_p=0.95,      
            do_sample=True ,   
            repetition_penalty=1.05
        )

    generated_ids_trimmed = [
        out_ids[len(in_ids):] for in_ids, out_ids in zip(inputs.input_ids, generated_ids)
    ]

    output_text = processor.batch_decode(generated_ids_trimmed, skip_special_tokens=True, clean_up_tokenization_spaces=False
    )[0]

    return output_text