In [2]:
!pip install pillow

Collecting pillow
  Downloading pillow-11.1.0-cp310-cp310-macosx_11_0_arm64.whl.metadata (9.1 kB)
Downloading pillow-11.1.0-cp310-cp310-macosx_11_0_arm64.whl (3.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 3.3 MB/s eta 0:00:00a 0:00:01
Installing collected packages: pillow
Successfully installed pillow-11.1.0

In [3]:
!pip install mistralai

Collecting mistralai
  Downloading mistralai-1.5.0-py3-none-any.whl.metadata (29 kB)
Collecting eval-type-backport>=0.2.0 (from mistralai)
  Using cached eval_type_backport-0.2.2-py3-none-any.whl.metadata (2.2 kB)
Collecting httpx>=0.27.0 (from mistralai)
  Downloading httpx-0.28.1-py3-none-any.whl.metadata (7.1 kB)
Collecting jsonpath-python>=1.0.6 (from mistralai)
  Using cached jsonpath_python-1.0.6-py3-none-any.whl.metadata (12 kB)
Collecting pydantic>=2.9.0 (from mistralai)
  Downloading pydantic-2.10.6-py3-none-any.whl.metadata (30 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/mohit/Documents/GitHub/ecdna-analysis/.venv/lib/python3.10/site-packages (from mistralai) (2.9.0.post0)
Collecting typing-inspect>=0.9.0 (from mistralai)
  Using cached typing_inspect-0.9.0-py3-none-any.whl.metadata (1.5 kB)
Collecting anyio (from httpx>=0.27.0->mistralai)
  Downloading anyio-4.8.0-py3-none-any.whl.metadata (4.6 kB)
Collecting certifi (from httpx>=0.27.0->mistralai)
  Downloading certifi-2025.1.31-py3-none-any.whl.metadata (2.5 kB)
Collecting httpcore==1.* (from httpx>=0.27.0->mistralai)
  Downloading httpcore-1.0.7-py3-none-any.whl.metadata (21 kB)
Collecting idna (from httpx>=0.27.0->mistralai)
  Downloading idna-3.10-py3-none-any.whl.metadata (10 kB)
Collecting h11<0.15,>=0.13 (from httpcore==1.*->httpx>=0.27.0->mistralai)
  Downloading h11-0.14.0-py3-none-any.whl.metadata (8.2 kB)
Collecting annotated-types>=0.6.0 (from pydantic>=2.9.0->mistralai)
  Using cached annotated_types-0.7.0-py3-none-any.whl.metadata (15 kB)
Collecting pydantic-core==2.27.2 (from pydantic>=2.9.0->mistralai)
  Using cached pydantic_core-2.27.2-cp310-cp310-macosx_11_0_arm64.whl.metadata (6.6 kB)
Requirement already satisfied: typing-extensions>=4.12.2 in /Users/mohit/Documents/GitHub/ecdna-analysis/.venv/lib/python3.10/site-packages (from pydantic>=2.9.0->mistralai) (4.12.2)
Requirement already satisfied: six>=1.5 in /Users/mohit/Documents/GitHub/ecdna-analysis/.venv/lib/python3.10/site-packages (from python-dateutil>=2.8.2->mistralai) (1.17.0)
Collecting mypy-extensions>=0.3.0 (from typing-inspect>=0.9.0->mistralai)
  Downloading mypy_extensions-1.0.0-py3-none-any.whl.metadata (1.1 kB)
Requirement already satisfied: exceptiongroup>=1.0.2 in /Users/mohit/Documents/GitHub/ecdna-analysis/.venv/lib/python3.10/site-packages (from anyio->httpx>=0.27.0->mistralai) (1.2.2)
Collecting sniffio>=1.1 (from anyio->httpx>=0.27.0->mistralai)
  Downloading sniffio-1.3.1-py3-none-any.whl.metadata (3.9 kB)
Downloading mistralai-1.5.0-py3-none-any.whl (271 kB)
Using cached eval_type_backport-0.2.2-py3-none-any.whl (5.8 kB)
Downloading httpx-0.28.1-py3-none-any.whl (73 kB)
Downloading httpcore-1.0.7-py3-none-any.whl (78 kB)
Using cached jsonpath_python-1.0.6-py3-none-any.whl (7.6 kB)
Downloading pydantic-2.10.6-py3-none-any.whl (431 kB)
Using cached pydantic_core-2.27.2-cp310-cp310-macosx_11_0_arm64.whl (1.8 MB)
Using cached typing_inspect-0.9.0-py3-none-any.whl (8.8 kB)
Using cached annotated_types-0.7.0-py3-none-any.whl (13 kB)
Downloading mypy_extensions-1.0.0-py3-none-any.whl (4.7 kB)
Downloading anyio-4.8.0-py3-none-any.whl (96 kB)
Downloading idna-3.10-py3-none-any.whl (70 kB)
Downloading certifi-2025.1.31-py3-none-any.whl (166 kB)
Using cached h11-0.14.0-py3-none-any.whl (58 kB)
Downloading sniffio-1.3.1-py3-none-any.whl (10 kB)
Installing collected packages: sniffio, pydantic-core, mypy-extensions, jsonpath-python, idna, h11, eval-type-backport, certifi, annotated-types, typing-inspect, pydantic, httpcore, anyio, httpx, mistralai
Successfully installed annotated-types-0.7.0 anyio-4.8.0 certifi-2025.1.31 eval-type-backport-0.2.2 h11-0.14.0 httpcore-1.0.7 httpx-0.28.1 idna-3.10 jsonpath-python-1.0.6 mistralai-1.5.0 mypy-extensions-1.0.0 pydantic-2.10.6 pydantic-core-2.27.2 sniffio-1.3.1 typing-inspect-0.9.0

In [5]:
!pip install requests

Collecting requests
  Using cached requests-2.32.3-py3-none-any.whl.metadata (4.6 kB)
Collecting charset-normalizer<4,>=2 (from requests)
  Downloading charset_normalizer-3.4.1-cp310-cp310-macosx_10_9_universal2.whl.metadata (35 kB)
Requirement already satisfied: idna<4,>=2.5 in /Users/mohit/Documents/GitHub/ecdna-analysis/.venv/lib/python3.10/site-packages (from requests) (3.10)
Collecting urllib3<3,>=1.21.1 (from requests)
  Downloading urllib3-2.3.0-py3-none-any.whl.metadata (6.5 kB)
Requirement already satisfied: certifi>=2017.4.17 in /Users/mohit/Documents/GitHub/ecdna-analysis/.venv/lib/python3.10/site-packages (from requests) (2025.1.31)
Using cached requests-2.32.3-py3-none-any.whl (64 kB)
Downloading charset_normalizer-3.4.1-cp310-cp310-macosx_10_9_universal2.whl (198 kB)
Downloading urllib3-2.3.0-py3-none-any.whl (128 kB)
Installing collected packages: urllib3, charset-normalizer, requests
Successfully installed charset-normalizer-3.4.1 requests-2.32.3 urllib3-2.3.0

In [ ]:
from PIL import Image

import base64
import os
import requests
import pandas as pd
import time

from pydantic import BaseModel

from mistralai import Mistral
from utils import read_red_channel, read_green_channel, read_blue_channel, generate_random_sample

In [16]:
# Helper function
def encode_image(image_path):
    """Encode the image to base64."""
    try:
        with open(image_path, "rb") as image_file:
            return base64.b64encode(image_file.read()).decode('utf-8')
    except FileNotFoundError:
        print(f"Error: The file {image_path} was not found.")
        return None
    except Exception as e:  # Added general exception handling
        print(f"Error: {e}")
        return None

# Specify model
model = "pixtral-12b-2409"

# Path to your image
image_path = "data/converted/19.jpg"

# Getting the base64 string
base64_image = encode_image(image_path)

api_key = os.environ["PIXTRAL"]
client = Mistral(api_key=api_key)

## Demo

In [ ]:
# Define the messages for the chat
messages = [
    {
        "role": "user",
        "content": [
            {
                "type": "text",
                "text": "For this task, act as a bioligist who is studying extrachromosomal DNA (ecDNA). Consider this metaphase image containing ecDNA. Analyze it for possible ecDNA."
            },
            {
                "type": "image_url",
                "image_url": f"data:image/jpeg;base64,{base64_image}" 
            }
        ]
    }
]

# Get the chat response
chat_response = client.chat.complete(
    model=model,
    messages=messages
)

# Print the content of the response
print(chat_response.choices[0].message.content)

In [94]:
def generate_response(client, model, img_path, prompt, context, response_format=None, temp=0.7):
    
    # Encode image
    img_input = encode_image(img_path)
    
    # Define the messages for the chat
    messages = [
        {
            "role":"system",
            "content": f'{context}'
            
        },
        {
            "role": "user",
            "content": [
                {
                    "type": "text",
                    "text": f"{prompt}"
                },
                {
                    "type": "image_url",
                    "image_url": f"data:image/jpeg;base64,{img_input}" 
                }
            ]
        }
    ]
    
    # Get the chat response
    chat_response = client.chat.complete(
        model=model,
        temperature=temp,
        messages=messages
    )

    # Return the content of the response
    return chat_response.choices[0].message.content

### Experiment #1: 0-Shot Learning

In [103]:
# Load the data
test_labels_path = '/Users/mohit/Documents/GitHub/ecdna-analysis/test_im_data/test_im_ec_quantification.csv'
labels_df = pd.read_csv(test_labels_path, header=0, names=['img','ec'])
labels_df['img'] = labels_df['img'].apply(lambda x: x[:-4])
labels_df.head()

    img  ec
0     0   1
1     1   3
2    10   2
3  1000   2
4  1001   0

In [96]:
def pixtral_zero_shot(data_folder, runs):
    ec_predictions = []
    counter = 0
    
    context = """
            For this task, you will act as a pathologist who is studying 
            extrachromosomal DNA (ecDNA). You will be given multiple images
            and asked to identify the number of circular ecDNA structures.
            ecDNA is usually smaller than chromosomes or nuclei which are also present.
            """
    prompt = "Count the number of ecDNA in this image. Output only a single integer and no additional text."
    
    model = "pixtral-12b-2409"
    api_key = os.environ["PIXTRAL"]
    client = Mistral(api_key=api_key)
    
    for img in os.listdir(data_folder):
        if img.endswith('.png'):    
            print(img)
            
            img_path = os.path.join(data_folder, img)
            result = generate_response(client, model, img_path, prompt, context)
            ec_predictions.append(result)
            
            time.sleep(1)
            counter += 1

        if counter == runs:
            break
        
    return ec_predictions

In [104]:
test_folder = '/Users/mohit/Documents/GitHub/ecdna-analysis/test_im_data/labels'
sampled_path = './data/sampled'
sample_data = generate_random_sample(input_folder=test_folder, output_folder=sampled_path, sample_size=10)

preds = pixtral_zero_shot(sampled_path, 10)
preds

2379
2014.png
1849.png
849.png
1714.png
1854.png
743.png
1411.png
2050.png

['17', '12', '1', '5', '4', '2', '4', '15']

In [105]:
labels_df.head()

    img  ec
0     0   1
1     1   3
2    10   2
3  1000   2
4  1001   0

In [ ]:
for img in os.listdir('./data/sampled'):
    if img.endswith()
    labels_df[labels_df['img'].isin(preds)]

Empty DataFrame
Columns: [img, ec]
Index: []